name: Conftest Test

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "**/*.yaml"
      - "**/*.yml"
      - "**/*.json"
      - "policy/**"
  pull_request:
    branches: [main]
    paths:
      - "**/*.yaml"
      - "**/*.yml"
      - "**/*.json"
      - "**/policy/**"

jobs:
  conftest:
    name: Conftest Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Run Conftest Test
        uses: ./conftest
        with:
          path: "."
          policy-path: "./tests/policy"
          output-format: "github"
          fail-on-warn: "false"
          all-namespaces: "true"
