name: Regal Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/*.rego"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.rego"

jobs:
  regal:
    name: Regal Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Run Regal Test
        uses: ./regal
        with:
          path: "./tests/policy"
          output-format: "github"
          regal-version: "latest"
