name: Renovate Test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"

jobs:
  renovate:
    runs-on: ubuntu-latest
    name: Renovate Action
    permissions:
      contents: read
      pull-requests: write
      issues: write
      checks: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Run Renovate Test
        uses: ./renovate
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          autodiscover: "true"
          dry-run: "false"
          log-level: "info"
