name: Semantic-Release Test

on:
  workflow_dispatch:
  push:
    branches: [main, next, beta, alpha]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Semantic Release Action
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Run Semantic Release Test
        uses: ./semantic-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-file: semantic-release/config/releaserc.json
          dry-run: "false"
