name: Semgrep Test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    name: Semgrep Action
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Run Semgrep Test
        uses: ./semgrep
        with:
          path: "."
          config: "auto"
          metrics: "off"
          no-secrets-validation: "true"
        continue-on-error: true

      - name: Upload SARIF (if produced)
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: semgrep-results.sarif
        continue-on-error: true
